Storage module updates
Apillon/sdk pull request #19
Opened 2023-12-04 14:06 UTC by dimitrov-d

- Added file.delete() method
- Added bucket.directory() method
- Added directory.delete() method
- Updated bucket endpoints and JSDoc comments
- IPNS SDK method and CLI commands

2023-12-05 10:31 UTC, MoMannn commented on packages/sdk/src/modules/storage/directory.ts
> +    this.API_PREFIX = `/storage/buckets/${bucketUuid}/directories/${directoryUuid}`;
Why is this not: `this.API_PREFIX = /storage/buckets/${bucketUuid}` Then the prefix used in get? I know that base here is directory but if you need a lower level prefix for an api call it should probably stay as that lower level.

2023-12-05 10:32 UTC, MoMannn commented on packages/sdk/src/modules/storage/directory.ts
> -      `${this.API_PREFIX}/content`,
So why is prefix not used here?

2023-12-05 11:34 UTC, MoMannn approved these changes

2023-12-08 08:00 UTC, MoMannn approved these changes

2023-12-08 08:53 UTC, tinemlakar requested changes

2023-12-08 08:53 UTC, tinemlakar commented on packages/cli/README.md
> -        run: npx --yes @apillon/cli hosting deploy-website ./dist --uuid $WEBSITE_UUID --key $APILLON_API_KEY --secret $APILLON_API_SECRET
this should be fine as it was!

2023-12-08 08:53 UTC, tinemlakar commented on packages/cli/src/modules/storage/ipns.commands.ts
> +    .option('-c, --cid <cid>', 'CID to which this IPNS name will point')
description could be just "Targeted CID"

2023-12-08 08:53 UTC, tinemlakar commented on packages/cli/src/modules/storage/ipns.commands.ts
> +      'CID to which this IPNS name will point',
Same as above

2023-12-08 08:53 UTC, tinemlakar commented on packages/sdk/README.md
> +} from "@apillon/sdk";
Why double quotes?!

2023-12-08 08:53 UTC, tinemlakar commented on packages/sdk/README.md
> +::: warning
thos should be properly formatted for markdown. For example with md quote:

```
> ***Warning***
> this is the warning!
```

> ***Warning***
> this is the warning!

2023-12-08 10:19 UTC, tinemlakar approved these changes

2023-12-08 10:19 UTC, merged